import { motion, useScroll, useTransform, useSpring, useInView, Variants } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
  Zap, Target, Users, Shield, ArrowRight, CheckCircle, Heart,
  Utensils, Sparkles, Activity, TrendingUp
} from 'lucide-react';
import { useRef, useState, useEffect } from 'react';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import { useAuth } from '../context/AuthContext';

export default function Home() {
  const { user } = useAuth();
  const [mousePosition, setMousePosition] = useState({ x: 0, y: 0 });
  const containerRef = useRef<HTMLDivElement>(null);

  const { scrollYProgress } = useScroll();
  // Use section ref for hero (section element)
  const heroRef = useRef<HTMLElement>(null);
  const isHeroInView = useInView(heroRef, { once: false });

  // Parallax & fade
  const opacity = useTransform(scrollYProgress, [0, 0.5], [1, 0]);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      const el = containerRef.current;
      if (el) {
        const rect = el.getBoundingClientRect();
        setMousePosition({
          x: e.clientX - rect.left,
          y: e.clientY - rect.top
        });
      }
    };

    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  const springConfig = { damping: 20, stiffness: 300 };
  const mouseX = useSpring(mousePosition.x, springConfig);
  const mouseY = useSpring(mousePosition.y, springConfig);

  const features = [
    {
      icon: <Zap className="w-6 h-6 text-emerald-600" />,
      title: "AI-Powered Planning",
      description: "Get personalized meal and workout plans generated by advanced AI algorithms."
    },
    {
      icon: <Target className="w-6 h-6 text-blue-600" />,
      title: "TDEE Calculator",
      description: "Accurate calorie calculations using the scientifically-proven Mifflin-St Jeor equation."
    },
    {
      icon: <Users className="w-6 h-6 text-orange-600" />,
      title: "Athlete-Specific",
      description: "Tailored recommendations for runners, weightlifters, and general fitness enthusiasts."
    },
    {
      icon: <Shield className="w-6 h-6 text-purple-600" />,
      title: "Dietary Preferences",
      description: "Support for vegetarian, vegan, pescatarian, and non-vegetarian diets with allergy considerations."
    }
  ];

  const sdgGoals = [
    {
      number: "SDG-2",
      title: "Zero Hunger",
      icon: <Utensils className="w-8 h-8 text-emerald-600" />,
      description: "NutriGuide addresses food insecurity by making nutrition planning accessible to everyone, promoting sustainable food systems and ensuring nutritious, affordable meal options for all economic backgrounds."
    },
    {
      number: "SDG-3",
      title: "Good Health and Well-being",
      icon: <Heart className="w-8 h-8 text-red-600" />,
      description: "Our platform promotes physical and mental well-being through evidence-based nutrition and fitness recommendations, helping reduce diet-related diseases and improving overall quality of life."
    }
  ];

  const benefits = [
    "Personalized nutrition plans based on your unique profile",
    "Scientific TDEE calculations for accurate calorie tracking",
    "Budget-friendly meal suggestions with local ingredient focus",
    "Comprehensive exercise recommendations for all fitness levels",
    "Real-time progress tracking and goal management",
    "Expert-backed nutrition advice powered by AI"
  ];

  // Animation variants
  const fadeInUp: Variants = {
    hidden: { opacity: 0, y: 60 },
    visible: {
      opacity: 1, y: 0,
      transition: { duration: 0.8, ease: [0.25, 0.1, 0.25, 1.0] }
    }
  };

  const staggerContainer: Variants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: { staggerChildren: 0.2, delayChildren: 0.3 }
    }
  };

  const scaleIn: Variants = {
    hidden: { scale: 0.8, opacity: 0 },
    visible: {
      scale: 1, opacity: 1,
      transition: { duration: 0.6, ease: [0.25, 0.1, 0.25, 1.0] }
    }
  };

  const slideInLeft: Variants = {
    hidden: { x: -100, opacity: 0 },
    visible: {
      x: 0, opacity: 1,
      transition: { duration: 0.8, ease: [0.25, 0.1, 0.25, 1.0] }
    }
  };

  const slideInRight: Variants = {
    hidden: { x: 100, opacity: 0 },
    visible: {
      x: 0, opacity: 1,
      transition: { duration: 0.8, ease: [0.25, 0.1, 0.25, 1.0] }
    }
  };

  return (
    <div className="min-h-screen overflow-hidden" ref={containerRef}>
      {/* Animated Background Elements */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <motion.div
          className="absolute -top-40 -right-40 w-80 h-80 bg-emerald-300 rounded-full mix-blend-multiply filter blur-xl opacity-30"
          animate={{ x: [0, 100, 0], y: [0, -100, 0] }}
          transition={{ duration: 20, repeat: Infinity, repeatType: "reverse" }}
        />
        <motion.div
          className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-300 rounded-full mix-blend-multiply filter blur-xl opacity-30"
          animate={{ x: [0, -100, 0], y: [0, 100, 0] }}
          transition={{ duration: 25, repeat: Infinity, repeatType: "reverse" }}
        />
        <motion.div
          className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-purple-300 rounded-full mix-blend-multiply filter blur-xl opacity-20"
          animate={{ scale: [1, 1.2, 1] }}
          transition={{ duration: 15, repeat: Infinity, repeatType: "reverse" }}
        />
      </div>

      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-emerald-50 via-white to-blue-50 py-20 overflow-hidden" ref={heroRef}>
        <motion.div
          className="absolute inset-0 bg-gradient-to-r from-emerald-500/10 to-blue-500/10"
          style={{ opacity }}
        />
        {/* Floating particles */}
        {isHeroInView && Array.from({ length: 20 }).map((_, i) => (
          <motion.div
            key={`particle-${i}`}
            className="absolute rounded-full bg-white"
            style={{
              width: Math.random() * 6 + 2,
              height: Math.random() * 6 + 2,
              left: `${Math.random() * 100}%`,
              top: `${Math.random() * 100}%`,
            }}
            animate={{ y: [0, -100, 0], opacity: [0, 1, 0] }}
            transition={{
              duration: Math.random() * 10 + 10,
              repeat: Infinity,
              delay: Math.random() * 5,
            }}
          />
        ))}

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center">
            <motion.h1
              className="text-4xl md:text-6xl font-bold text-gray-900 mb-6"
              initial="hidden"
              animate="visible"
              variants={fadeInUp}
            >
              Your AI-Powered
              <span className="text-emerald-600 block">Nutrition & Fitness Companion</span>
            </motion.h1>
            <motion.p
              className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed"
              initial="hidden"
              animate="visible"
              variants={fadeInUp}
              transition={{ delay: 0.2 }}
            >
              Transform your health journey with personalized meal plans, scientifically-calculated nutrition goals,
              and AI-generated fitness recommendations tailored to your unique lifestyle and goals.
            </motion.p>
            <motion.div
              className="flex flex-col sm:flex-row gap-4 justify-center"
              initial="hidden"
              animate="visible"
              variants={fadeInUp}
              transition={{ delay: 0.4 }}
            >
              <Link to={user ? "/dashboard" : "/auth?mode=signup"}>
                <Button size="lg" className="w-full sm:w-auto group relative overflow-hidden">
                  <span className="relative z-10 flex items-center">
                    Start Your Journey
                    <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                  </span>
                  <motion.div
                    className="absolute inset-0 bg-emerald-700"
                    initial={{ x: "-100%" }}
                    whileHover={{ x: 0 }}
                    transition={{ duration: 0.3 }}
                  />
                </Button>
              </Link>
              <Link to="/demo">
                <Button variant="outline" size="lg" className="w-full sm:w-auto group relative overflow-hidden">
                  <span className="relative z-10">Try Demo</span>
                  <motion.div
                    className="absolute inset-0 bg-gray-100"
                    initial={{ x: "-100%" }}
                    whileHover={{ x: 0 }}
                    transition={{ duration: 0.3 }}
                  />
                </Button>
              </Link>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-white relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <motion.h2
              className="text-3xl md:text-4xl font-bold text-gray-900 mb-4"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
            >
              Powerful Features for Your Success
            </motion.h2>
            <motion.p
              className="text-lg text-gray-600 max-w-2xl mx-auto"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              transition={{ delay: 0.2 }}
            >
              Everything you need to achieve your health and fitness goals in one comprehensive platform.
            </motion.p>
          </div>

          <motion.div
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={staggerContainer}
          >
            {features.map((feature) => (
              <motion.div
                key={feature.title}
                variants={scaleIn}
                whileHover={{ y: -10, transition: { duration: 0.3 } }}
              >
                <Card className="text-center h-full overflow-hidden group relative">
                  <div className="absolute inset-0 bg-gradient-to-br from-transparent to-emerald-50 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  <div className="relative z-10">
                    <motion.div
                      className="flex justify-center mb-4"
                      whileHover={{ scale: 1.2, rotate: 5 }}
                      transition={{ type: "spring", stiffness: 300 }}
                    >
                      {feature.icon}
                    </motion.div>
                    <h3 className="font-semibold text-lg mb-3">{feature.title}</h3>
                    <p className="text-gray-600 text-sm">{feature.description}</p>
                  </div>
                </Card>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* SDG Goals Section */}
      <section className="py-16 bg-gradient-to-r from-emerald-50 to-blue-50 relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <motion.h2
              className="text-3xl md:text-4xl font-bold text-gray-900 mb-4"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
            >
              Aligned with UN Sustainable Development Goals
            </motion.h2>
            <motion.p
              className="text-lg text-gray-600 max-w-3xl mx-auto"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={fadeInUp}
              transition={{ delay: 0.2 }}
            >
              NutriGuide contributes to global sustainability by addressing critical health and nutrition challenges
              outlined in the United Nations Sustainable Development Goals.
            </motion.p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {sdgGoals.map((goal, idx) => (
              <motion.div
                key={goal.number}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                variants={idx === 0 ? slideInLeft : slideInRight}
                whileHover={{ scale: 1.03 }}
              >
                <Card className="h-full overflow-hidden group">
                  <div className="absolute inset-0 bg-gradient-to-br from-transparent to-emerald-50 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                  <div className="relative z-10 flex items-start space-x-4">
                    <motion.div
                      className="flex-shrink-0"
                      whileHover={{ rotate: 15, scale: 1.2 }}
                      transition={{ type: "spring", stiffness: 300 }}
                    >
                      {goal.icon}
                    </motion.div>
                    <div>
                      <div className="flex items-center space-x-2 mb-2">
                        <span className="bg-emerald-100 text-emerald-800 text-sm font-medium px-2 py-1 rounded">
                          {goal.number}
                        </span>
                        <h3 className="font-semibold text-lg">{goal.title}</h3>
                      </div>
                      <p className="text-gray-600 leading-relaxed">{goal.description}</p>
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 bg-white relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={slideInLeft}
            >
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
                Why Choose NutriGuide?
              </h2>
              <p className="text-lg text-gray-600 mb-8">
                Join thousands of users who have transformed their health with our evidence-based,
                AI-powered approach to nutrition and fitness planning.
              </p>
              <ul className="space-y-4">
                {benefits.map((benefit, idx) => (
                  <motion.li
                    key={benefit}
                    className="flex items-start space-x-3"
                    initial="hidden"
                    whileInView="visible"
                    viewport={{ once: true }}
                    variants={fadeInUp}
                    transition={{ delay: idx * 0.1 }}
                    whileHover={{ x: 10 }}
                  >
                    <motion.div
                      whileHover={{ scale: 1.2, rotate: 10 }}
                      transition={{ type: "spring", stiffness: 300 }}
                    >
                      <CheckCircle className="w-5 h-5 text-emerald-600 mt-0.5 flex-shrink-0" />
                    </motion.div>
                    <span className="text-gray-700">{benefit}</span>
                  </motion.li>
                ))}
              </ul>
            </motion.div>
            <motion.div
              className="relative"
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              variants={slideInRight}
            >
              <motion.div
                className="bg-gradient-to-br from-emerald-400 to-blue-500 rounded-2xl p-8 text-white relative overflow-hidden"
                whileHover={{ scale: 1.02 }}
                style={{
                  transform: `rotateY(${mouseX.get() / 50}deg) rotateX(${-mouseY.get() / 50}deg)`,
                  transformStyle: "preserve-3d"
                }}
              >
                <div className="absolute inset-0 bg-white/10 backdrop-blur-sm" />
                <div className="relative z-10 space-y-6">
                  <motion.div
                    className="bg-white/20 rounded-lg p-4 backdrop-blur-sm"
                    whileHover={{ scale: 1.05 }}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-semibold">Daily Calories</h4>
                      <Activity className="w-5 h-5" />
                    </div>
                    <div className="text-2xl font-bold mb-2">2,150</div>
                    <div className="bg-white/20 rounded-full h-2">
                      <motion.div
                        className="bg-white rounded-full h-2"
                        initial={{ width: 0 }}
                        whileInView={{ width: "75%" }}
                        viewport={{ once: true }}
                        transition={{ duration: 1, delay: 0.5 }}
                      />
                    </div>
                  </motion.div>
                  <motion.div
                    className="bg-white/20 rounded-lg p-4 backdrop-blur-sm"
                    whileHover={{ scale: 1.05 }}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-semibold">Today's Workout</h4>
                      <TrendingUp className="w-5 h-5" />
                    </div>
                    <p className="text-sm opacity-90">30 min strength training + 20 min cardio</p>
                  </motion.div>
                  <motion.div
                    className="bg-white/20 rounded-lg p-4 backdrop-blur-sm"
                    whileHover={{ scale: 1.05 }}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-semibold">Meal Plan Ready</h4>
                      <Sparkles className="w-5 h-5" />
                    </div>
                    <p className="text-sm opacity-90">7 days of personalized nutrition</p>
                  </motion.div>
                </div>
              </motion.div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-gray-900 text-white relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-r from-emerald-900/20 to-blue-900/20" />
        <motion.div
          className="absolute -top-40 -right-40 w-80 h-80 bg-emerald-500 rounded-full mix-blend-multiply filter blur-xl opacity-20"
          animate={{ x: [0, 100, 0], y: [0, -100, 0] }}
          transition={{ duration: 20, repeat: Infinity, repeatType: "reverse" }}
        />
        <motion.div
          className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-500 rounded-full mix-blend-multiply filter blur-xl opacity-20"
          animate={{ x: [0, -100, 0], y: [0, 100, 0] }}
          transition={{ duration: 25, repeat: Infinity, repeatType: "reverse" }}
        />

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <motion.h2
            className="text-3xl md:text-4xl font-bold mb-6"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={fadeInUp}
          >
            Ready to Transform Your Health?
          </motion.h2>
          <motion.p
            className="text-xl text-gray-300 mb-8 max-w-2xl mx-auto"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={fadeInUp}
            transition={{ delay: 0.2 }}
          >
            Join the NutriGuide community today and start your journey towards optimal health and wellness.
          </motion.p>
          <motion.div
            className="flex flex-col sm:flex-row gap-4 justify-center"
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            variants={staggerContainer}
          >
            <Link to={user ? "/dashboard" : "/auth?mode=signup"}>
              <Button size="lg" className="bg-emerald-600 hover:bg-emerald-700 w-full sm:w-auto group relative overflow-hidden">
                <span className="relative z-10 flex items-center">
                  Get Started Free
                  <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                </span>
                <motion.div
                  className="absolute inset-0 bg-emerald-700"
                  initial={{ x: "-100%" }}
                  whileHover={{ x: 0 }}
                  transition={{ duration: 0.3 }}
                />
              </Button>
            </Link>
            <Link to="/demo">
              <Button variant="outline" size="lg" className="border-gray-600 text-gray-300 hover:bg-gray-800 w-full sm:w-auto group relative overflow-hidden">
                <span className="relative z-10">Explore Demo</span>
                <motion.div
                  className="absolute inset-0 bg-gray-800"
                  initial={{ x: "-100%" }}
                  whileHover={{ x: 0 }}
                  transition={{ duration: 0.3 }}
                />
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
}